LangString LauncherFileNotFound ${LANG_KOREAN} "${PORTABLEAPPNAME}(을)를 실행할 수 없습니다. 프로그램을 다시 설치해 주십시오. (에러: $MISSINGFILEORPATH(을)를 찾을 수 없습니다)"
LangString LauncherAlreadyRunning ${LANG_KOREAN} "${APPNAME}의 다른 인스턴스가 이미 실행 중입니다. 먼저 ${APPNAME}의 다른 인스턴스를 닫은 후 ${PORTABLEAPPNAME}(을)를 실행하십시오."
LangString LauncherAskCopyLocal ${LANG_KOREAN} "${PORTABLEAPPNAME} appears to be running from a location that is read-only. Would you like to temporarily copy it to the local hard drive and run it from there?$\n$\nPrivacy Note: If you say Yes, your personal data within ${PORTABLEAPPNAME} will be temporarily copied to a local drive. Although this copy of your data will be deleted when you close ${PORTABLEAPPNAME}, it may be possible for someone else to access your data later."
LangString LauncherNoReadOnly ${LANG_KOREAN} "${PORTABLEAPPNAME} can not run directly from a read-only location and will now close."
LangString LauncherPathTooLong ${LANG_KOREAN} "The path to ${PORTABLEAPPNAME} is too long.  Please shorten the path by eliminating some parent directories or shortening directory names."
LangString LauncherNextButton ${LANG_KOREAN} "&Next >"
